pin "sweetalert2", to: "https://ga.jspm.io/npm:sweetalert2@11.10.3/dist/sweetalert2.all.js"
# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin "@rails/ujs", to: "https://ga.jspm.io/npm:@rails/ujs@6.1.0/lib/assets/compiled/rails-ujs.js"
pin "jquery", to: "jquery.js"
## pin "datatables.net", to: "datatables.min.js"
## pin "bootstrap", to: "bootstrap.min.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "suppliers_datatable", to: "suppliers_datatable.js"
pin "suppliers_create", to: "suppliers_create.js"
pin "jquery", to: "https://ga.jspm.io/npm:jquery@3.7.1/dist/jquery.js"
